lib/cocu_web/router.ex
defmodule CocuWeb.Router do
  use CocuWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug CocuWeb.SaveLocale
  end

  pipeline :api do
    plug :fetch_session
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :accepts, ["json"]
  end

  pipeline :auth do
    plug Cocu.Auth.Pipeline
  end

  pipeline :ensure_auth do
    plug Guardian.Plug.EnsureAuthenticated, handler: __MODULE__
  end

  scope "/", CocuWeb do
    pipe_through [:browser, :auth] # Use the default browser stack

    get "/explore", ExploreController, :index
    get "/manage", ManageController, :index
    get "/", PageController, :index
    resources "/community", CommunityController
    get "/project/show/:id", ProjectController, :show
    resources "/media", MediaController
    resources "/user", UserController, only: [:index, :new, :create]
    post "/user/login", UserController, :login
    resources "/pagenotfound", PageNotFoundController

  end

  scope "/api", CocuWeb do
    pipe_through [:api, :auth]

    scope "/v1", V1, as: :v1 do
      get "/post/:id", PostController, :getPostById
      post "/project/donation", ProjectController, :donate
      get "/post/replies/:id", PostController, :getPostReplies
      get "/explore", ExploreController, :getProjects
      get "/communities", CommunityController, :get_communities
      get "/manage/communities", ManageController, :getCommunities
      get "/manage/projects", ManageController, :getCommunitiesProjects
      get "/project/backers", ProjectController, :getBackers
    end
  end

  scope "/api", CocuWeb do
    pipe_through [:api, :auth, :ensure_auth]

    scope "/v1", V1, as: :v1 do
      post "/community_post/new", CommunityPostController, :addCommunityPost
      put "/community_post/edit/:id", CommunityPostController, :editCommunityPost
      delete "/community_post/delete/:id", CommunityPostController, :deleteCommunityPost
      post "/post_reply/new", PostReplyController, :addPostReply
      get "/post_reply/:id", PostReplyController, :getPostReplyById
      put "/post_reply/edit/:id", PostReplyController, :editPostReply
      delete "/post_reply/delete/:id", PostReplyController, :deletePostReply
      put "/project/:id/state/:state", ProjectController, :updateProjectState
      put "/project/:id/deleted/:deleted", ProjectController, :updateProjectDeleted
      put "/project/connect/:id", ProjectController, :connect
      put "/user/:id/deleted/:deleted", UserController, :updateUserDeleted
      post "/user/follow_community/toggle_follow/:community_id", CommunityUsersController, :toggle_follow
      get "/community/get_followers", CommunityUsersController, :get_followers
      post "/community/invite_user/", UserInviteController, :invite_user_to_community
      post "/community/remove_user", CommunityUsersController, :remove_user
      post "/vote/project/:project_id/rate/:rate", VoteController, :userRateProject
      post "/user/follow_community/accept_invitation/:community_id", CommunityUsersController, :accept_invitation
      post "/user/follow_community/reject_invitation/:community_id", CommunityUsersController, :reject_invitation
      get "/community_post/get_page/", CommunityPostController, :get_by_page
      get "/project_post/get_page", ProjectPostController, :get_by_page
      put "/project_post/edit/:id", ProjectPostController, :editProjectPost
      post "/project_post/new", ProjectPostController, :addProjectPost
      delete "/project_post/delete/:id", ProjectPostController, :deleteProjectPost
      put "/manage/updateAcceptance", ManageController, :updateProjectAcceptance
      delete "/community/delete/:id", CommunityController, :deleteCommunity
      get "/community/get_n_projects", CommunityController, :get_n_projects
      get "/community/search", CommunityUsersController, :get_available_communities
      put "/manage/deleteProject/:id", ManageController, :deleteProject
    end
  end

  #Routes that require authentication
  scope "/", CocuWeb do
    pipe_through [:browser, :auth, :ensure_auth]
    resources "/project", ProjectController,  only: [:edit, :delete, :update, :new, :create]
    resources "/project", ProjectController, only: [:edit, :delete, :update, :new, :create]
    resources "/user", UserController, only: [:show, :edit, :delete, :update]
    get "/project/donation", ProjectController, :donate
    get "/project/donation/finished", ProjectController, :donation_finished
    get "/project/connect", ProjectController, :connect_stripe_acc
    post "/project/disconnect/:id", ProjectController, :disconnect_stripe_acc
    post "/user/logout", UserController, :logout
    post "/user/follow_community/:community_id", CommunityUserController, :follow_community
    put "/user/:id/update_password", UserController, :update_password
    put "/user/:id/update_picture", UserController, :update_picture
  end

  scope "/", CocuWeb do
    get "/*path", PageNotFoundController, :error
  end
end

lib/cocu_web/controllers/layout_controller.ex
defmodule CocuWeb.LayoutController do
    use CocuWeb, :controller

end

lib/cocu_web/views/layout_view.ex
defmodule CocuWeb.LayoutView do
  use CocuWeb, :view

  @doc """
  Generates name for the JavaScript view we want to use
  in this combination of view/template.
  """
  def js_view_name(conn) do
    [view_name(conn)]
    |> Enum.reverse
    |> List.insert_at(0, "view")
    |> Enum.map(&String.capitalize/1)
    |> Enum.reverse
    |> Enum.join("")
  end

  # Takes the resource name of the view module and removes the
  # the ending *_view* string.
  defp view_name(conn) do
    conn
    |> view_module
    |> Phoenix.Naming.resource_name
    |> String.replace("_view", "")
  end

  defp get_locale(conn) do
    conn
    |> Plug.Conn.get_session(:locale)
  end

  @doc """
  Fetches the communities the user is subscribed to
  """
  def list_user_communities(user_id) do
    user_id
    |> Cocu.CommunityUsers.get_user_communities 
  end

  def display_user_community([id, name]) do
    ~e"""
    <a class="item" href="/community/<%=id%>"><%=name%></a>
    """
  end

  def get_notification_count(user_id) do
    Cocu.CommunityInvitations.get_invite_count user_id
  end
  
end

lib/cocu_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="apple-touch-icon" sizes="57x57" href="images/favicon/apple-icon-57x57.png">
      <link rel="apple-touch-icon" sizes="60x60" href="images/favicon/apple-icon-60x60.png">
      <link rel="apple-touch-icon" sizes="72x72" href="images/favicon/apple-icon-72x72.png">
      <link rel="apple-touch-icon" sizes="76x76" href="images/favicon/apple-icon-76x76.png">
      <link rel="apple-touch-icon" sizes="114x114" href="images/favicon/apple-icon-114x114.png">
      <link rel="apple-touch-icon" sizes="120x120" href="images/favicon/apple-icon-120x120.png">
      <link rel="apple-touch-icon" sizes="144x144" href="images/favicon/apple-icon-144x144.png">
      <link rel="apple-touch-icon" sizes="152x152" href="images/favicon/apple-icon-152x152.png">
      <link rel="apple-touch-icon" sizes="180x180" href="images/favicon/apple-icon-180x180.png">
      <link rel="icon" type="image/png" sizes="192x192" href="images/favicon/android-icon-192x192.png">
      <link rel="icon" type="image/png" sizes="32x32" href="images/favicon/favicon-32x32.png">
      <link rel="icon" type="image/png" sizes="96x96" href="images/favicon/favicon-96x96.png">
      <link rel="icon" type="image/png" sizes="16x16" href="images/favicon/favicon-16x16.png">
      <link rel="manifest" href="/manifest.json">
      <meta name="msapplication-TileColor" content="#ffffff">
      <meta name="msapplication-TileImage" content="/ms-icon-144x144.png">
      <meta name="theme-color" content="#ffffff">

    <%= if title = @conn.assigns[:page_title] do  %>
    <title> <%= title %> </title>
    <% else %>
    <title> Cocu </title>
    <% end %>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:100,400,600,900" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Fredoka+One" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Muli:200,400" rel="stylesheet">


  </head>

  <body data-js-view-name="<%= js_view_name(@conn) %>">

    <meta name="csrf" content="<%= Plug.CSRFProtection.get_csrf_token() %>">
    <%= if Guardian.Plug.current_token(@conn) do %>
      <meta name='guardian_token' content="<%= Guardian.Plug.current_token(@conn) %>">
    <%end%>


    
     <%= render Elixir.CocuWeb.LayoutView, "header.html", assigns %>


    <main role="test">
        <%= if error = get_flash(@conn, :error) do %>
          <div class="ui negative message" role="alert">
        <% else %>
          <div class="ui negative message" role="alert" style="display: none;">
        <% end %>
            <i class="close icon"></i>
            <div class="header">
              <%= error %>
            </div>
          </div>

        <%= if warning = get_flash(@conn, :warning) do %>
          <div class="ui warning message" role="alert">
        <% else %>
          <div class="ui warning message" role="alert" style="display: none;">
        <% end %>
            <i class="close icon"></i>
            <div class="header">
              <%= warning %>
            </div>
          </div>
        <%= if info = get_flash(@conn, :info) do %>
          <div class="ui info message" role="alert">
        <% else %>
          <div class="ui info message" role="alert" style="display: none;">
        <% end %>
            <i class="close icon"></i>
            <div class="header">
              <%= info %>
            </div>
          </div>

        <%= if success = get_flash(@conn, :success) do %>
          <div class="ui success message" role="alert">
        <% else %>
          <div class="ui success message" role="alert" style="display: none;">
        <% end %>
            <i class="close icon"></i>
            <div class="header">
              <%= success %>
            </div>
          </div>


        <%= render @view_module, @view_template, assigns %>
    </main>

    <%= render Elixir.CocuWeb.LayoutView,  "footer.html", assigns %>

    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCDqTj7FTAm7YF7I6bdBi26Co8SpZc6MEs&sensor=false&libraries=places"></script>
    <script src="https://js.stripe.com/v3/"></script>
  </body>
</html>

lib/cocu_web/templates/layout/footer.html.eex
<div class="footer ui centered grid">
            <div class="center aligned column logo"><img class="ui large image" src="/images/logo.png"></div>

            <div class="stackable row links">
              <div class="center aligned column column-info"><a href="/">Home</a></div>
              <div class="center aligned column column-info"><a href="/explore">Projects</a></div>
              <div class="center aligned column column-info"><a href="/community">Communities</a></div>
            </div>
             <div class="stackable row icons">
              <div class="center aligned column column-info"><i class="facebook f icon"></i></div>
              <div class="center aligned column column-info"><i class="twitter icon"></i></div>
              <div class="center aligned column column-info"><i class="mail icon"></i></div>
            </div>
            <div class="row">
              <hr class="separator">
            </div>
            
             <div class="five wide column center aligned description"> Please join us in the co-creative universe </div>
</div>

lib/cocu_web/templates/layout/header.html.eex
<div id="nav-bar-header" class="ui stackable equal width grid computer only">
    <div class="middle aligned content column">
        <a id="logo" class="item" href="/">
            <span class="cocu">C</span>
            <span class="cocu-o">O</span>
            <span class="cocu">CU</span>
        </a>
        <%= if Guardian.Plug.current_resource(@conn) != nil do %>
            <% user_id = Guardian.Plug.current_resource(@conn).id %>
            <div id="user-communities" class="ui scrolling inline pointing dropdown">
                <div class="default text"><%= gettext "Your Communities"%></div>
                <i class="dropdown icon" ></i>
                <div class="menu menu-border">
                    <div id="user-community-search" class="ui icon search input">
                        <i class="search icon"></i>
                        <input placeholder="Search for a community..." type="text">
                    </div>
                    <%= list_user_communities(user_id) |> Enum.map(fn(x) -> display_user_community(x) end)%>
                </div>
            </div>
        <% end %>
        
        <div id="explore-dropdown-menu" class="ui scrolling inline pointing dropdown">
            <%= gettext "Explore" %>
            <i class="dropdown icon"></i>
            <div class="menu menu-border">
                <div class="item"><a class="item" href="/explore"><%= gettext "Projects" %></a></div>
                <div class="item"><a id="explore-communities" class="item" href="/community"><%= gettext "Communities" %></a></div>
            </div>
        </div>
        
    </div>
    <div class="center aligned middle aligned content column">
        <div id="search-bar" class="ui fluid large search">
            <div class="ui icon input">
                <%= if assigns[:project_search_name] do %>
                    <input id="name-project" value="<%= @project_search_name %>" class="prompt" type="text" placeholder='<%= gettext "Search For Projects..." %>'>
                <% else %>
                    <input id="name-project" class="prompt" type="text" placeholder='<%= gettext "Search For Projects..." %>'>
                <% end %>
                <i class="search icon"></i>
            </div>
            <div class="results"></div>
        </div>
    </div>
    <div class="middle aligned content right aligned column">
        <%= if Guardian.Plug.current_resource(@conn) != nil do %>
             <% id = Guardian.Plug.current_resource(@conn).id%>
            <% name = Guardian.Plug.current_resource(@conn).name %>
             <% first_name = Enum.at(String.split(name, " "),0) %>
             <% photo = Guardian.Plug.current_resource(@conn).picture_path %>
            <div id="nav-user-info">
               <%= if photo != nil do %>
                    <img class="ui avatar image" src="<%= photo %>">
                <% else %>
                <img class="ui avatar image" src="/images/default-user.png">
               <% end %>
               <div id="user-dropdown" class="ui inline pointing dropdown" >
                 <span><a><%= first_name %></a></span>
                <% [notification_count] = get_notification_count(id)%>
                <%= if notification_count > 0 do %>
                    <div id="nav-user-notification-count" class="ui circular segment">
                    <%= notification_count %>
                    </div>
                <%end%>
                 <i class="dropdown icon"></i>
                 <div id="user-dropdown-menu" class="menu menu-border">
                   <%= link (gettext "My Profile"), to: user_path(@conn, :edit, id), class: "item username-padding"%>
                   <%= link (gettext "Create Project"), to: project_path(@conn, :new), class: "item username-padding"%>
                   <%= link (gettext "Create Community"), to: community_path(@conn, :new), class: "item username-padding"%>
                   <%= link (gettext "Log Out"), to: user_path(@conn, :logout), method: :post, class: "item logout-button"%>
                 </div>
               </div>
          </div>
        <%end%>
         <%= if Guardian.Plug.current_resource(@conn) == nil do %>
             <%= link "Sign In", to: user_path(@conn, :index), class: "item sign-in-button", id: "sign-in-button-id" %>
             <%= link "Sign Up", to: user_path(@conn, :new), class: "item sign-up-button", id: "sign-up-button-id" %>
        <%end%>
        <div class="last-column-language">
        <div id="active-language">
            <%= if String.equivalent?(get_locale(@conn),"en") do %>
                <a class="english row item item-language">
                    <label class="language-name"><%= gettext "English" %></label>
                    <i class="gb flag"></i>
                    <i id="dropdown-icon-language" class="dropdown icon"></i>
                </a>
            <%end%>
            <%= if String.equivalent?(get_locale(@conn),"pt") do %>
                <a class="portuguese row item item-language">
                    <label class="language-name"><%= gettext "Portuguese" %></label>
                    <i class="pt flag"></i>
                    <i id="dropdown-icon-language" class="dropdown icon"></i>
                </a>
            <%end%>
             <%= if String.equivalent?(get_locale(@conn),"es") do %>
                <a class=" spanish row item item-language">
                    <label class="language-name"><%= gettext "Spanish" %></label>
                    <i class="es flag"></i>
                    <i id="dropdown-icon-language" class="dropdown icon"></i>
                </a>
            <%end%>
            <%= if String.equivalent?(get_locale(@conn),"nl") do %>
                <a class=" dutch row item item-language">
                    <label class="language-name"><%= gettext "Dutch" %></label>
                    <i class="nl flag"></i>
                    <i id="dropdown-icon-language" class="dropdown icon"></i>
                </a>
            <%end%>
        </div>
        </div>
        <div class="available-languages menu-border">
            <div class="ui grid link list">
                <%= if !String.equivalent?(get_locale(@conn),"en") do %>
                    <a class="english row item item-language" href=<%= "/en" <> assigns[:conn].request_path %>>
                        <label class="language-name"><%= gettext "English" %></label>
                        <i class="gb flag"></i>
                    </a>
                <%end %>

                <%= if !String.equivalent?(get_locale(@conn),"pt") do %>
                <a class="portuguese row item item-language" href=<%= "/pt" <> assigns[:conn].request_path %>>
                    <label class="language-name"><%= gettext "Portuguese" %></label>
                    <i class="pt flag"></i>
                </a>
                <%end%>

                <%= if !String.equivalent?(get_locale(@conn),"es") do %>
                <a class="spanish row item item-language" href=<%= "/es" <> assigns[:conn].request_path %>>
                    <label class="language-name"><%= gettext "Spanish" %></label>
                    <i class="es flag"></i>
                </a>
                <%end%>
                <%= if !String.equivalent?(get_locale(@conn),"nl") do %>
                <a class="dutch row item item-language" href=<%= "/nl" <> assigns[:conn].request_path %>>
                    <label class="language-name"><%= gettext "Dutch" %></label>
                    <i class="nl flag"></i>
                </a>
                <%end%>
            </div>
        </div>
    </div>
</div>

<div id="nav-bar-header-mobile" class="ui grid tablet mobile only">

    <a href="/" class="item logo">
            <span class="cocu">C</span>
            <span class="cocu-o">O</span>
            <span class="cocu">CU</span>
    </a>
    <div id="toggle">
        <div class="one"></div>
        <div class="two"></div>
        <div class="three"></div>
    </div>

    <div id="menu-mobile">
        <div class="middle aligned content column">
        <%= if Guardian.Plug.current_resource(@conn) != nil do %>
            <% user_id = Guardian.Plug.current_resource(@conn).id %>
            <div class="ui accordion">
                <div class="item title">
                    <%= gettext "Your Communities"%>
                </div>
                <div class="content">
                    <% user_communities = list_user_communities(user_id) %>
                    <%= user_communities
                        |> Enum.map(fn(x) -> display_user_community(x) end)%>
                </div>
            </div>
            <div class="ui divider"></div>
        <%end%>
            <a href="/explore" class="item"><%= gettext "Projects" %></a>
            <div class="ui divider"></div>
            <a href="/community" class="item"><%= gettext "Communities" %></a>
            <div class="ui divider"></div>
             <%= if Guardian.Plug.current_resource(@conn) != nil do %>
             <% id = Guardian.Plug.current_resource(@conn).id%>
             <div class="mobile-user">
              <% name = Guardian.Plug.current_resource(@conn).name %>
              <% first_name = Enum.at(String.split(name, " "),0) %>
                 <%= if photo != nil do %>
                 <img class="ui avatar image" src="<%= photo %>">
                 <% else %>
                 <img class="ui avatar image" src="/images/default-user.png">
                 <% end %>
               <%= link first_name, to: user_path(@conn, :edit, id), class: "item username-padding"%>
             </div>
             <div class="ui divider"></div>
            <div>
             <%= link (gettext "Create Project"), to: project_path(@conn, :new), class: "item"%>
             <div class="ui divider"></div>
             <%= link (gettext "Create Community"), to: community_path(@conn, :new), class: "item"%>
             <div class="ui divider"></div>
             <%= link (gettext "Log Out"), to: user_path(@conn, :logout), method: :post, class: "item"%>
             </div>
            <%end%>
            <%= if Guardian.Plug.current_resource(@conn) == nil do %>
                <%= link "Sign In", to: user_path(@conn, :index), class: "item"%>
                <div class="ui divider"></div>
                <%= link "Sign Up", to: user_path(@conn, :new), class: "item" %>
            <%end%>
          <div class="ui divider"></div>
            <div id="active-language">
                <%= if String.equivalent?(get_locale(@conn),"en") do %>
                <a class="english row item item-language">
                    <label class="language-name"><%= gettext "English" %></label>
                    <i class="gb flag"></i>
                    <i id="dropdown-icon-language" class="dropdown icon"></i>
                </a>
                <%end%>
                <%= if String.equivalent?(get_locale(@conn),"pt") do %>
                    <a class="portuguese row item item-language">
                        <label class="language-name"><%= gettext "Portuguese" %></label>
                        <i class="pt flag"></i>
                        <i id="dropdown-icon-language" class="dropdown icon"></i>
                    </a>
                <%end%>
                <%= if String.equivalent?(get_locale(@conn),"es") do %>
                    <a class=" spanish row item item-language">
                        <label class="language-name"><%= gettext "Spanish" %></label>
                        <i class="es flag"></i>
                        <i id="dropdown-icon-language" class="dropdown icon"></i>
                    </a>
                <%end%>
                <%= if String.equivalent?(get_locale(@conn),"nl") do %>
                    <a class=" dutch row item item-language">
                        <label class="language-name"><%= gettext "Dutch" %></label>
                        <i class="nl flag"></i>
                        <i id="dropdown-icon-language" class="dropdown icon"></i>
                    </a>
                <%end%>
            </div>
            <div class="available-languages">
                 <%= if !String.equivalent?(get_locale(@conn),"en") do %>
                    <a class="english row item item-language" href=<%= "/en" <> assigns[:conn].request_path %>>
                        <i class="gb flag"></i>
                        <label class="language-name"><%= gettext "English" %></label>
                    </a>
                <%end %>

                 <%= if !String.equivalent?(get_locale(@conn),"pt") do %>
                <a class="portuguese row item item-language" href=<%= "/pt" <> assigns[:conn].request_path %>>
                    <i class="pt flag"></i>
                    <label class="language-name"><%= gettext "Portuguese" %></label>
                </a>
                <%end%>

                 <%= if !String.equivalent?(get_locale(@conn),"es") do %>
                <a class="spanish row item item-language" href=<%= "/es" <> assigns[:conn].request_path %>>
                    <i class="es flag"></i>
                    <label class="language-name"><%= gettext "Spanish" %></label>
                </a>
                <%end%>
                 <%= if !String.equivalent?(get_locale(@conn),"nl") do %>
                <a class="dutch row item item-language" href=<%= "/nl" <> assigns[:conn].request_path %>>
                    <i class="nl flag"></i>
                    <label class="language-name"><%= gettext "Dutch" %></label>
                </a>
                <%end%>
            </div>
        </div>
    </div>
</div>